__author__ = 'Administrator'
#encoding: utf-8
#==============================================首页元素==============================================
#==========================header==========================
#logo
logo_locator="//img[@class='school_logo']"
#首页登录按钮
login_locator="//span[@class='tips02']"
#首页登录后用户信息
userinfo_locator="//span[@class='fast_login_msg']"
#微信登录按钮
WXlogin_locator="//span[@class='icon-weChat']"
#qq登录按钮
QQlogin_locator="//span[@class='icon-qq']"
#搜索框
searchbox_locator="//input[@class='search_import']"
#搜索按钮
searchbtn_locator="//span[@class='search_btn']"
#==========================导航栏==========================
#首页按钮
homebtn_locator="//span[text()='首页']"
#导航栏菜单
home_firstnav_locator="//ul[@class='first_nav']/li[1]"
#导航栏弹框第一个分类
home_secondnav_content_locator="//ul[@class='first_nav']/li[1]//ul/li[1]"
#==========================自定义项==========================
#网上报名系统
home_custom1_locator="//span[text()='网上报名系统 ']"
#网上报名系统link
home_custom1_link_locator="//span[text()='网上报名系统 ']//parent::a"
#录取查询系统
home_custom2_locator="//span[text()='录取查询系统']"
#录取查询系统link
home_custom2_link_locator="//span[text()='录取查询系统']//parent::a"
#=======================右侧悬浮栏==========================
#右侧悬浮机器人
right_robot_locator="//div[@class='floatItem01']"
#机器人判断提示框
robot_content_locator="//div[@class='contents']"
#登录按钮
content_login_locator="//div[@class='contents']//span[text()=' 登录']"
#注册按钮
content_register_locator="//div[@class='contents']//span[text()='注册']"
#二维码按钮
right_qrcode_locator="//div[@class='floatItem02']"
#二维码弹框
right_qrcode_content_locator="//img[@class='erweima']"
#常见问题
right_hot_locator="//div[@class='floatItem03 usericon-webicon-70']"
#=========================招录公告============================
#模块名
enrollNotice_locator="//span[text()='招录公告']"
#加载更多
enrollNotice_more_locator="//a[@class='more icon-jia']"
#第一篇文章标题
first_Enroll_title_locator="//div[@class='hot_message_content']//li[1]//span[@class='hot_message_title']"
#第二篇文章标题
second_Enroll_title_locator="//div[@class='hot_message_content']//li[2]//span[@class='hot_message_title']"
#第三篇文章标题
third_Enroll_title_locator="//div[@class='hot_message_content']//li[3]//span[@class='hot_message_title']"
#=========================快捷入口============================
#第一个分类
quick_firstnav_locator="//div[@class='hot_quick_container']/ul/li[1]/div[@class='hot_quick_item']"
#悬浮后文章列表的显示
quick_firstnav_on_locator="//div[@class='hot_quick_container']/ul/li[1]/div[@class='hot_quick_itemList']"
#悬浮后分类名
quick_firstnav_name_locator="//div[@class='hot_quick_container']/ul/li[1]//span[@class='tips01']"
#悬浮后更多按钮
quick_firstnav_more_locator="//div[@class='hot_quick_container']/ul/li[1]//a[@class='itemList_more']"
#第一个分类的第一篇文章
quick_firstnav_firsttitle_locator="//div[@class='hot_quick_container']/ul/li[1]//ul[@class='itemList_msg']/li[1]"
#=========================招生快讯============================
#分类
alerts_nav_locator="//ul[@class='admissionsNews_firstItems']/li"
#当前分类名
alerts_firstNav_locator="//a[@class='title active']"
#第二个分类名
alerts_secondNav_locator="//a[@class='title']"
#第一篇文章
alerts_firstArticle_locator="//a[@class='title active']//following-sibling::div//a[@class='msg01']"
#第二篇文章
alerts_secondArticle_locator="//a[@class='title active']//following-sibling::div//li[1]//span[@class='tips01']"
#=========================招生简章============================
#名
rules_nav_locator="//span[text()='简章']"
#文章   li标签有1-7个
rules_article_locator="//div[@class='admissionBrochures_itemList']/ul/li[1]//div[@class='title01']"
#=========================视频在线============================
#名
vedio_nav_locator="//span[text()='视频在线']"
#第一个视频
vedio_first_locator="//div[@class='videoList_item']/a[1]"
#图片
vedio_first_img_locator="//div[@class='videoList_item']/a[1]/img"
#第二个视频
vedio_second_locator="//div[@class='videoList_item']/a[2]"
#图片
vedio_second_img_locator="//div[@class='videoList_item']/a[2]/img"
#=========================智能在线============================
#左边文字
robot_left_locator="//div[@class='robot_left']"
#中间按钮
robot_btn_locatpr="//a[@class='robot_btn']"
#电话咨询
robot_phone_locator="//span[text()='电话咨询']"
#电话咨询弹框
robot_phonecontent_locator="//span[text()='电话咨询']//following-sibling::div"
#邮件咨询
robot_email_locator="//span[text()='邮件咨询']"
#邮件咨询弹框
robot_emailcontent_locator="//span[text()='邮件咨询']//following-sibling::div"
#留言咨询
robot_message_locator="//span[text()='留言咨询']"
#留言咨询弹框
robot_messagecontent_locator="//span[text()='留言咨询']//following-sibling::div"
#留言咨询对话框
message_content_locator="//div[@class='advice_box01']"
#进入留言咨询界面
robot_toMessage_locator="//div[text()='点击进入留言咨询']"
#=========================人物============================
#箭头
teacher_left_locator="//span[text()='‹']"
teacher_right_locator="//span[text()='›']"
#默认第一张图
teacher_firstImg_locator="//ul[@class='JQ-slide-content']/li[1]//span[@class='desc01']"
#第一篇文章标题
teacher_firstTitle_locator="//ul[@class='JQ-slide-content']/li[1]//span[@class='name']"
#默认第一张图
teacher_secondImg_locator="//ul[@class='JQ-slide-content']/li[2]//span[@class='desc01']"
#第二篇文章标题
teacher_secondTitle_locator="//ul[@class='JQ-slide-content']/li[2]//span[@class='name']"
#了解更多按钮
teacher_firstImgBtn_locator="//ul[@class='JQ-slide-content']/li[1]//span[@class='more_btn']"
#=========================故事============================
#图片
story_img_locator="//img[@class='culture_title_img']"
#模块名
story_nav_locator="//div[@class='culture_title_content']/span"
#文字主体
story_content_locator="//div[@class='culture_content']"
#第一篇标题
story_firsttitle_locator="//div[@class='culture_content']/span[@class='title01']"
#第二篇
story_secondtitle_locator="//div[@class='culture_content']/div[@class='msg02']/ul/li[1]"
#=========================校园风采============================
#风采图
picture_locator="//div[@class='Scenery']"
#==============================================登录页==============================================
#登录页标识
login_title_locator="//p[@class='login_title']"
#==========================账号密码登录tab==========================
login_account_locator="//a[text()='账号密码登录']"
#账号输入框
login_username_input_locator="//input[@class='login_username_input']"
#密码输入框
login_psw_input_locator="//input[@class='login_password_input']"
#登录按钮
login_btn_locator="//a[@class='login_btn']"
#出错提示
login_error_locator="//span[@class='login_error']"
#免费注册按钮
login_register_locator="//a[text()='免费注册']"
#==========================快捷登录tab==============================
login_quick_locator="//a[text()='快捷登录']"
#微信登录
login_WX_locator="//div[@class='login_wechat']"
#微信二维码
login_WXqrcode_locator="//img[@class='qrcode lightBorder']"
#qq登录
login_qq_locator="//div[@class='login_qq']"
#qq登录信息
login_qq_img_locator="//a[text()='帐号密码登录']"

#=================================================注册页=================================================
#注册页面title
register_title_locator="//p[@class='register_titles']"

#==============================================二级页面元素==============================================
#==========================内容详情页==============================
#面包屑
first_catnav="//a[@class='aur']"
second_catnav="//a[@class='cur']"
#内容详情id
content_locator="//div[@class='Article_details_content_artical']"
#文章标题
title_locator="//h1[@class='tips01']"
#==========================左侧菜单栏==============================
#当前所属一级菜单
leftnav_locator="//span[@class='side_bar_tips']"

#============================================机器人页面元素==============================================
#转招办人工答疑按钮
robot_toRengong_locator="//span[text()='转招办人工答疑']"
#常见问题列表   id
robot_freqlist_locator="freq-list"